### PR TITLE
Fixing norch not listening to other than localhost

### PR DESCRIPTION
**Pull request by eklem**
... localhost/127.0.0.1

### CODE REVIEW

**Comment by eklem** [comment]
Fixing https://github.com/fergiemcdowall/norch/issues/136

**Comment by fergiemcdowall** [comment]
Tests definitely need to be improved to pick this up

**Comment by eklem** [comment]
I guess it's a little hard to test since you need it running on a server different from where the tests are running?

**Comment by fergiemcdowall** [comment]
Yes- its tricky, but it _seems_ doable http://stackoverflow.com/questions/12173990/how-can-you-debug-a-cors-request-with-curl

**Pull request merged**
